version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: dockersample
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  app:
    image: wahyuuk/sample-docker
    depends_on: 
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/dockersample?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8081:8080"
